CREATE TABLE IF NOT EXISTS `mid_every_counties_CAGR` (
  `ID` int(4) DEFAULT NULL,
  `CITY` varchar(10) DEFAULT NULL,
  `DISTRICT` varchar(20) DEFAULT NULL,
  `RANK` int(4) DEFAULT NULL,
  `COUNTY_CAGR` varchar(20) DEFAULT NULL,
  `2014` varchar(20) DEFAULT NULL,
  `2015` varchar(20) DEFAULT NULL,
  `2016` varchar(20) DEFAULT NULL,
  `2017` varchar(20) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;